language: python

python:
  - "3.4"

env:
  matrix:
    - DJANGO="Django<1.9,>=1.8"
    - DJANGO="Django<1.10,>=1.9"
    - DJANGO="-e git+https://github.com/django/django.git@master#egg=Django"
matrix:
  fast_finish: true
  allow_failures:
    - env: DJANGO="-e git+https://github.com/django/django.git@master#egg=Django"
install:
  - pip install --upgrade pip
  - pip install -r requirements-dev.txt
  - pip install $DJANGO
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34

install: pip install tox

script: tox

notifications:
  email: false
deploy:
  provider: pypi
  user: kocicjelena
  password:
    secure: 
  on:
    tags: true
    branch: master
