language: python

python:
  - "3.6"

env:
  - TOXENV=py27
  - TOXENV=py36



before_install:
  - sudo apt-get install python-dev 
install: 
 - python setup.py install
 - pip install tox

script: 
  - tox

notifications:
  email: false

