language: python

python:
  - "3.4"

env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34

install: pip install tox

script: tox

notifications:
  email: false
deploy:
  provider: pypi
  user: kocicjelena
  password:
    secure: 
  on:
    tags: true
    branch: master
